### ISSUE TITLE
sorting does not work

### ISSUE THREAD

**Issue by phil-newman** [musement/api-documentation#15]
Try to sort the results using different properties but results are always the same:
```
https://developers.musement.com/api/v3/cities/1/events.json?vertical=3&sorting=popularity
https://developers.musement.com/api/v3/cities/1/events.json?vertical=3&sorting=price
https://developers.musement.com/api/v3/cities/1/events.json?vertical=3&sorting=rating
```

**Comment by hpatoio** [comment]
Ciao. We are working on this. I'll ping you when is ready.

**Comment by phil-newman** [comment]
> PS: If you can do not call the endpoint using the extension .json or .xml but use the Accept header.

Where is this documented? Looking at http://developers.musement.com/documentation suggests that you can specify the response type using an extension, header or querystring param. Which of these is true and what is the order of precedence?

**Comment by hpatoio** [comment]
>   Where is this documented? Looking at http://developers.musement.com/documentation suggests that you can specify the response type using an extension, header or querystring param. Which of these is true and what is the order of precedence?

Ciao. You are right. This is not written explicitly in our doc but use `Accept` header to tell the server which format you want in the response is a best practice for RESTful web service. 

The file format and the parameter are easier methods for non smart clients.

**Comment by hpatoio** [comment]
Should be ok now

```
https://developers.musement.com/api/v3/cities/1/events.json?sort_by=relevance
https://developers.musement.com/api/v3/cities/1/events.json?sort_by=rating
https://developers.musement.com/api/v3/cities/1/events.json?sort_by=price
```

Please note that the parameter is called `sort_by` and not  `sorting`
